use super::super::super::{DeploymentManifest, SIGNER_SIDECAR_ROOT};
use super::super::quote::{sh_arg_list_suffix, sh_command_tokens, sh_literal};

pub(in crate::private_network) fn render_unix_start_script(
    manifest: &DeploymentManifest,
) -> String {
    let mut text = format!(
        "#!/usr/bin/env sh\nset -eu\n\n# Generated by NeoNexus for {} / magic {}.\ncd \"$(dirname \"$0\")\"\nif [ \"${{NEONEXUS_SKIP_PREFLIGHT:-0}}\" != \"1\" ]; then\n  ./preflight-unix.sh\nfi\n\nstart_signer() {{\n  label=\"$1\"\n  binary=\"$2\"\n  shift 2\n  workdir=\"{SIGNER_SIDECAR_ROOT}/$label\"\n  mkdir -p \"$workdir\"\n  stdout=\"$workdir/$label.out.log\"\n  stderr=\"$workdir/$label.err.log\"\n  pid_file=\"$workdir/$label.pid\"\n  echo \"Starting signer $label\"\n  nohup \"$binary\" \"$@\" > \"$stdout\" 2> \"$stderr\" &\n  echo $! > \"$pid_file\"\n}}\n\nstart_node() {{\n  name=\"$1\"\n  workdir=\"$2\"\n  shift 2\n  mkdir -p \"$workdir\"\n  stdout=\"$workdir/$name.out.log\"\n  stderr=\"$workdir/$name.err.log\"\n  pid_file=\"$workdir/$name.pid\"\n  echo \"Starting $name\"\n  (\n    cd \"$workdir\"\n    nohup \"$@\" > \"$stdout\" 2> \"$stderr\" &\n    echo $! > \"$pid_file\"\n  )\n}}\n\n",
        manifest.runtime, manifest.network_magic
    );
    append_unix_start_signers(&mut text, manifest);
    for node in &manifest.nodes {
        text.push_str(&format!(
            "start_node {} {} {}\n",
            sh_literal(&node.name),
            sh_literal(&node.working_dir),
            sh_command_tokens(&node.binary_path, &node.arguments)
        ));
    }
    text.push_str(
        "\nif [ \"${NEONEXUS_SKIP_HEALTH:-0}\" != \"1\" ]; then\n  ./health-unix.sh\nfi\n",
    );
    text
}

pub(in crate::private_network) fn render_unix_stop_script(manifest: &DeploymentManifest) -> String {
    let mut text = format!(
        "#!/usr/bin/env sh\nset -eu\n\n# Generated by NeoNexus for {} / magic {}.\ncd \"$(dirname \"$0\")\"\n\nstop_pid_file() {{\n  label=\"$1\"\n  pid_file=\"$2\"\n  if [ ! -f \"$pid_file\" ]; then\n    echo \"No PID file for $label\"\n    return 0\n  fi\n  pid=\"$(cat \"$pid_file\")\"\n  if kill -0 \"$pid\" 2>/dev/null; then\n    echo \"Stopping $label pid=$pid\"\n    kill \"$pid\"\n  else\n    echo \"$label pid=$pid is not running\"\n  fi\n  rm -f \"$pid_file\"\n}}\n\nstop_node() {{\n  name=\"$1\"\n  workdir=\"$2\"\n  stop_pid_file \"$name\" \"$workdir/$name.pid\"\n}}\n\nstop_signer() {{\n  label=\"$1\"\n  stop_pid_file \"signer $label\" \"{SIGNER_SIDECAR_ROOT}/$label/$label.pid\"\n}}\n\n",
        manifest.runtime, manifest.network_magic
    );
    for node in manifest.nodes.iter().rev() {
        text.push_str(&format!(
            "stop_node {} {}\n",
            sh_literal(&node.name),
            sh_literal(&node.working_dir)
        ));
    }
    append_unix_stop_signers(&mut text, manifest);
    text
}

fn append_unix_start_signers(text: &mut String, manifest: &DeploymentManifest) {
    let signers = manifest
        .committee
        .signers
        .iter()
        .filter_map(|signer| {
            signer
                .signer_command_plan
                .as_ref()
                .map(|plan| (signer, plan))
        })
        .collect::<Vec<_>>();
    if signers.is_empty() {
        return;
    }
    text.push_str("# Committee signer sidecars\n");
    for (signer, plan) in signers {
        text.push_str(&format!(
            "start_signer {} {}{}\n",
            sh_literal(&signer.label),
            sh_literal(&plan.binary),
            sh_arg_list_suffix(&plan.arguments)
        ));
    }
    text.push('\n');
}

fn append_unix_stop_signers(text: &mut String, manifest: &DeploymentManifest) {
    let signers = manifest
        .committee
        .signers
        .iter()
        .filter(|signer| signer.signer_command_plan.is_some())
        .collect::<Vec<_>>();
    if signers.is_empty() {
        return;
    }
    text.push_str("\n# Committee signer sidecars\n");
    for signer in signers.into_iter().rev() {
        text.push_str(&format!("stop_signer {}\n", sh_literal(&signer.label)));
    }
}
