use crate::*;

#[test]
fn event_kind_parses_role_application_audit_events() {
    assert_eq!(
        EventKind::from_str("node-restarted").unwrap(),
        EventKind::NodeRestarted
    );
    assert_eq!(
        EventKind::from_str("plugin-installed").unwrap(),
        EventKind::PluginInstalled
    );
    assert_eq!(
        EventKind::from_str("role-applied").unwrap(),
        EventKind::RoleApplied
    );
    assert_eq!(
        EventKind::from_str("private-network-materialized").unwrap(),
        EventKind::PrivateNetworkMaterialized
    );
    assert_eq!(
        EventKind::from_str("private-network-launch-pack-exported").unwrap(),
        EventKind::PrivateNetworkLaunchPackExported
    );
    assert_eq!(
        EventKind::from_str("private-network-launch-pack-validated").unwrap(),
        EventKind::PrivateNetworkLaunchPackValidated
    );
    assert_eq!(
        EventKind::from_str("snapshot-saved").unwrap(),
        EventKind::SnapshotSaved
    );
    assert_eq!(
        EventKind::from_str("snapshot-verified").unwrap(),
        EventKind::SnapshotVerified
    );
    assert_eq!(
        EventKind::from_str("snapshot-downloaded").unwrap(),
        EventKind::SnapshotDownloaded
    );
    assert_eq!(
        EventKind::from_str("snapshot-cached").unwrap(),
        EventKind::SnapshotCached
    );
    assert_eq!(
        EventKind::from_str("snapshot-applied").unwrap(),
        EventKind::SnapshotApplied
    );
    assert_eq!(
        EventKind::from_str("config-applied").unwrap(),
        EventKind::ConfigApplied
    );
    assert_eq!(
        EventKind::from_str("node-ports-assigned").unwrap(),
        EventKind::NodePortsAssigned
    );
    assert_eq!(
        EventKind::from_str("runtime-installed").unwrap(),
        EventKind::RuntimeInstalled
    );
    assert_eq!(
        EventKind::from_str("runtime-downloaded").unwrap(),
        EventKind::RuntimeDownloaded
    );
    assert_eq!(
        EventKind::from_str("runtime-applied").unwrap(),
        EventKind::RuntimeApplied
    );
    assert_eq!(
        EventKind::from_str("runtime-state-reconciled").unwrap(),
        EventKind::RuntimeStateReconciled
    );
    assert_eq!(
        EventKind::from_str("runtime-smoke-tested").unwrap(),
        EventKind::RuntimeSmokeTested
    );
    assert_eq!(
        EventKind::from_str("runtime-upgrade-policy-updated").unwrap(),
        EventKind::RuntimeUpgradePolicyUpdated
    );
    assert_eq!(
        EventKind::from_str("runtime-upgrade-policy-run").unwrap(),
        EventKind::RuntimeUpgradePolicyRun
    );
    assert_eq!(
        EventKind::from_str("neo-wallet-profile-imported").unwrap(),
        EventKind::NeoWalletProfileImported
    );
    assert_eq!(
        EventKind::from_str("neo-wallet-profile-used").unwrap(),
        EventKind::NeoWalletProfileUsed
    );
    assert_eq!(
        EventKind::from_str("neo-wallet-profile-deleted").unwrap(),
        EventKind::NeoWalletProfileDeleted
    );
    assert_eq!(
        EventKind::from_str("rpc-health-checked").unwrap(),
        EventKind::RpcHealthChecked
    );
    assert_eq!(
        EventKind::from_str("rpc-health-monitor-policy-updated").unwrap(),
        EventKind::RpcHealthMonitorPolicyUpdated
    );
    assert_eq!(
        EventKind::from_str("alert-routing-policy-updated").unwrap(),
        EventKind::AlertRoutingPolicyUpdated
    );
    assert_eq!(
        EventKind::from_str("remote-server-created").unwrap(),
        EventKind::RemoteServerCreated
    );
    assert_eq!(
        EventKind::from_str("remote-server-updated").unwrap(),
        EventKind::RemoteServerUpdated
    );
    assert_eq!(
        EventKind::from_str("remote-server-probed").unwrap(),
        EventKind::RemoteServerProbed
    );
    assert_eq!(
        EventKind::from_str("remote-federation-monitor-policy-updated").unwrap(),
        EventKind::RemoteFederationMonitorPolicyUpdated
    );
    assert_eq!(
        EventKind::from_str("remote-server-deleted").unwrap(),
        EventKind::RemoteServerDeleted
    );
    assert_eq!(
        EventKind::from_str("workspace-readiness-report-exported").unwrap(),
        EventKind::WorkspaceReadinessReportExported
    );
    assert_eq!(
        EventKind::from_str("workspace-integrity-checked").unwrap(),
        EventKind::WorkspaceIntegrityChecked
    );
    assert_eq!(
        EventKind::from_str("support-bundle-exported").unwrap(),
        EventKind::SupportBundleExported
    );
    assert_eq!(
        EventKind::from_str("event-journal-exported").unwrap(),
        EventKind::EventJournalExported
    );
    assert_eq!(
        EventKind::from_str("release-packaged").unwrap(),
        EventKind::ReleasePackaged
    );
    assert_eq!(
        EventKind::from_str("release-package-verified").unwrap(),
        EventKind::ReleasePackageVerified
    );
}
