use super::super::super::{DeploymentManifest, SIGNER_SIDECAR_ROOT};
use super::super::quote::{ps_array, ps_literal};

pub(in crate::private_network) fn render_windows_start_script(
    manifest: &DeploymentManifest,
) -> String {
    let mut text = format!(
        "$ErrorActionPreference = 'Stop'\n\n# Generated by NeoNexus for {} / magic {}.\nSet-Location $PSScriptRoot\nif ($env:NEONEXUS_SKIP_PREFLIGHT -ne '1') {{\n    & (Join-Path $PSScriptRoot 'preflight-windows.ps1')\n}}\n\nfunction Start-NeoNexusSigner {{\n    param(\n        [string]$Label,\n        [string]$Binary,\n        [string[]]$Args\n    )\n    $workDir = Join-Path '{SIGNER_SIDECAR_ROOT}' $Label\n    New-Item -ItemType Directory -Force -Path $workDir | Out-Null\n    $stdout = Join-Path $workDir \"$Label.out.log\"\n    $stderr = Join-Path $workDir \"$Label.err.log\"\n    $pidFile = Join-Path $workDir \"$Label.pid\"\n    Write-Host \"Starting signer $Label\"\n    $process = Start-Process -FilePath $Binary -ArgumentList $Args -WorkingDirectory $PSScriptRoot -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru\n    Set-Content -Path $pidFile -Value $process.Id\n}}\n\nfunction Start-NeoNexusNode {{\n    param(\n        [string]$Name,\n        [string]$WorkDir,\n        [string]$Binary,\n        [string[]]$Args\n    )\n    New-Item -ItemType Directory -Force -Path $WorkDir | Out-Null\n    $stdout = Join-Path $WorkDir \"$Name.out.log\"\n    $stderr = Join-Path $WorkDir \"$Name.err.log\"\n    $pidFile = Join-Path $WorkDir \"$Name.pid\"\n    Write-Host \"Starting $Name\"\n    $process = Start-Process -FilePath $Binary -ArgumentList $Args -WorkingDirectory $WorkDir -RedirectStandardOutput $stdout -RedirectStandardError $stderr -PassThru\n    Set-Content -Path $pidFile -Value $process.Id\n}}\n\n",
        manifest.runtime, manifest.network_magic
    );
    append_windows_start_signers(&mut text, manifest);
    for node in &manifest.nodes {
        text.push_str(&format!(
            "Start-NeoNexusNode -Name {} -WorkDir {} -Binary {} -Args @({})\n",
            ps_literal(&node.name),
            ps_literal(&node.working_dir),
            ps_literal(&node.binary_path),
            ps_array(&node.arguments)
        ));
    }
    text.push_str(
        "\nif ($env:NEONEXUS_SKIP_HEALTH -ne '1') {\n    & (Join-Path $PSScriptRoot 'health-windows.ps1')\n}\n",
    );
    text
}

pub(in crate::private_network) fn render_windows_stop_script(
    manifest: &DeploymentManifest,
) -> String {
    let mut text = format!(
        "$ErrorActionPreference = 'Stop'\n\n# Generated by NeoNexus for {} / magic {}.\nSet-Location $PSScriptRoot\n\nfunction Stop-NeoNexusPidFile {{\n    param(\n        [string]$Label,\n        [string]$PidFile\n    )\n    if (!(Test-Path $PidFile)) {{\n        Write-Host \"No PID file for $Label\"\n        return\n    }}\n    $pidValue = Get-Content -Path $PidFile -Raw\n    $pidValue = $pidValue.Trim()\n    if ([string]::IsNullOrWhiteSpace($pidValue)) {{\n        Remove-Item -Path $PidFile -Force\n        return\n    }}\n    $process = Get-Process -Id ([int]$pidValue) -ErrorAction SilentlyContinue\n    if ($null -ne $process) {{\n        Write-Host \"Stopping $Label pid=$pidValue\"\n        Stop-Process -Id ([int]$pidValue) -ErrorAction Stop\n    }} else {{\n        Write-Host \"$Label pid=$pidValue is not running\"\n    }}\n    Remove-Item -Path $PidFile -Force\n}}\n\nfunction Stop-NeoNexusNode {{\n    param(\n        [string]$Name,\n        [string]$WorkDir\n    )\n    Stop-NeoNexusPidFile -Label $Name -PidFile (Join-Path $WorkDir \"$Name.pid\")\n}}\n\nfunction Stop-NeoNexusSigner {{\n    param([string]$Label)\n    Stop-NeoNexusPidFile -Label \"signer $Label\" -PidFile (Join-Path (Join-Path '{SIGNER_SIDECAR_ROOT}' $Label) \"$Label.pid\")\n}}\n\n",
        manifest.runtime, manifest.network_magic
    );
    for node in manifest.nodes.iter().rev() {
        text.push_str(&format!(
            "Stop-NeoNexusNode -Name {} -WorkDir {}\n",
            ps_literal(&node.name),
            ps_literal(&node.working_dir)
        ));
    }
    append_windows_stop_signers(&mut text, manifest);
    text
}

fn append_windows_start_signers(text: &mut String, manifest: &DeploymentManifest) {
    let signers = manifest
        .committee
        .signers
        .iter()
        .filter_map(|signer| {
            signer
                .signer_command_plan
                .as_ref()
                .map(|plan| (signer, plan))
        })
        .collect::<Vec<_>>();
    if signers.is_empty() {
        return;
    }
    text.push_str("# Committee signer sidecars\n");
    for (signer, plan) in signers {
        text.push_str(&format!(
            "Start-NeoNexusSigner -Label {} -Binary {} -Args @({})\n",
            ps_literal(&signer.label),
            ps_literal(&plan.binary),
            ps_array(&plan.arguments)
        ));
    }
    text.push('\n');
}

fn append_windows_stop_signers(text: &mut String, manifest: &DeploymentManifest) {
    let signers = manifest
        .committee
        .signers
        .iter()
        .filter(|signer| signer.signer_command_plan.is_some())
        .collect::<Vec<_>>();
    if signers.is_empty() {
        return;
    }
    text.push_str("\n# Committee signer sidecars\n");
    for signer in signers.into_iter().rev() {
        text.push_str(&format!(
            "Stop-NeoNexusSigner -Label {}\n",
            ps_literal(&signer.label)
        ));
    }
}
