use super::super::super::{render::is_posix_absolute_path, DeploymentManifest};
use super::super::quote::ps_literal;

pub(in crate::private_network) fn render_windows_preflight_script(
    manifest: &DeploymentManifest,
) -> String {
    let mut text = format!(
        "$ErrorActionPreference = 'Stop'\n\n# Generated by NeoNexus for {} / magic {}.\nSet-Location $PSScriptRoot\n$Failures = 0\n\nfunction Fail-NeoNexusCheck {{\n    param([string]$Message)\n    Write-Host \"FAIL: $Message\"\n    $script:Failures += 1\n}}\n\nfunction Ok-NeoNexusCheck {{\n    param([string]$Message)\n    Write-Host \"OK: $Message\"\n}}\n\nfunction Warn-NeoNexusCheck {{\n    param([string]$Message)\n    Write-Host \"WARN: $Message\"\n}}\n\nfunction Test-NeoNexusFile {{\n    param([string]$Label, [string]$Path)\n    if (Test-Path -LiteralPath $Path -PathType Leaf) {{\n        Ok-NeoNexusCheck \"$Label exists\"\n    }} else {{\n        Fail-NeoNexusCheck \"$Label missing: $Path\"\n    }}\n}}\n\nfunction Test-NeoNexusSha256 {{\n    param([string]$Label, [string]$Path, [string]$Expected)\n    if (!(Test-Path -LiteralPath $Path -PathType Leaf)) {{\n        Fail-NeoNexusCheck \"$Label sha256 skipped; file missing: $Path\"\n        return\n    }}\n    try {{\n        $actual = (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()\n    }} catch {{\n        Fail-NeoNexusCheck \"$Label sha256 could not be computed: $($_.Exception.Message)\"\n        return\n    }}\n    $expectedNormalized = $Expected.ToLowerInvariant()\n    if ($actual -eq $expectedNormalized) {{\n        Ok-NeoNexusCheck \"$Label sha256 matches\"\n    }} else {{\n        Fail-NeoNexusCheck \"$Label sha256 mismatch: expected $expectedNormalized got $actual\"\n    }}\n}}\n\nfunction Test-NeoNexusDirectory {{\n    param([string]$Label, [string]$Path)\n    if (Test-Path -LiteralPath $Path -PathType Container) {{\n        Ok-NeoNexusCheck \"$Label exists\"\n    }} else {{\n        Fail-NeoNexusCheck \"$Label missing: $Path\"\n    }}\n}}\n\nfunction Test-NeoNexusPid {{\n    param([string]$Name, [string]$WorkDir)\n    $pidFile = Join-Path $WorkDir \"$Name.pid\"\n    if (!(Test-Path -LiteralPath $pidFile -PathType Leaf)) {{\n        Ok-NeoNexusCheck \"$Name has no active PID file\"\n        return\n    }}\n    $pidValue = (Get-Content -LiteralPath $pidFile -Raw).Trim()\n    if ([string]::IsNullOrWhiteSpace($pidValue)) {{\n        Warn-NeoNexusCheck \"$Name has an empty PID file: $pidFile\"\n        return\n    }}\n    $process = Get-Process -Id ([int]$pidValue) -ErrorAction SilentlyContinue\n    if ($null -ne $process) {{\n        Fail-NeoNexusCheck \"$Name already appears to be running with pid $pidValue\"\n    }} else {{\n        Warn-NeoNexusCheck \"$Name has a stale PID file: $pidFile\"\n    }}\n}}\n\nfunction Test-NeoNexusPort {{\n    param([string]$Label, [int]$Port)\n    $listener = $null\n    try {{\n        $endpoint = [System.Net.IPEndPoint]::new([System.Net.IPAddress]::Parse('127.0.0.1'), $Port)\n        $listener = [System.Net.Sockets.TcpListener]::new($endpoint)\n        $listener.Start()\n        Ok-NeoNexusCheck \"$Label port $Port is free\"\n    }} catch {{\n        Fail-NeoNexusCheck \"$Label port $Port is already listening on 127.0.0.1\"\n    }} finally {{\n        if ($null -ne $listener) {{ $listener.Stop() }}\n    }}\n}}\n\nfunction Test-NeoNexusSignerEndpoint {{\n    param([string]$Label, [string]$Endpoint)\n    $timeoutSeconds = 3\n    if (![string]::IsNullOrWhiteSpace($env:NEONEXUS_SIGNER_TIMEOUT_SECONDS)) {{\n        $timeoutSeconds = [int]$env:NEONEXUS_SIGNER_TIMEOUT_SECONDS\n    }}\n    $client = [System.Net.Http.HttpClient]::new()\n    try {{\n        $client.Timeout = [TimeSpan]::FromSeconds($timeoutSeconds)\n        $response = $client.GetAsync($Endpoint).GetAwaiter().GetResult()\n        Ok-NeoNexusCheck \"$Label endpoint reachable\"\n        $response.Dispose()\n    }} catch {{\n        Fail-NeoNexusCheck \"$Label endpoint unreachable: $Endpoint\"\n    }} finally {{\n        $client.Dispose()\n    }}\n}}\n\nfunction Test-NeoNexusSignerCommand {{\n    param([string]$Label, [string]$Binary)\n    if ([string]::IsNullOrWhiteSpace($Binary)) {{\n        Fail-NeoNexusCheck \"$Label sidecar binary missing\"\n        return\n    }}\n    if ($Binary.Contains('/') -or $Binary.Contains('\\') -or [System.IO.Path]::IsPathRooted($Binary)) {{\n        if (Test-Path -LiteralPath $Binary -PathType Leaf) {{\n            Ok-NeoNexusCheck \"$Label sidecar binary exists\"\n        }} else {{\n            Fail-NeoNexusCheck \"$Label sidecar binary missing: $Binary\"\n        }}\n        return\n    }}\n    if ($null -ne (Get-Command $Binary -ErrorAction SilentlyContinue)) {{\n        Ok-NeoNexusCheck \"$Label sidecar binary is on PATH\"\n    }} else {{\n        Fail-NeoNexusCheck \"$Label sidecar binary not found on PATH: $Binary\"\n    }}\n}}\n\n",
        manifest.runtime, manifest.network_magic
    );
    for node in &manifest.nodes {
        text.push_str(&format!(
            "Test-NeoNexusFile -Label {} -Path {}\nTest-NeoNexusFile -Label {} -Path {}\nTest-NeoNexusSha256 -Label {} -Path {} -Expected {}\nTest-NeoNexusDirectory -Label {} -Path {}\nTest-NeoNexusPid -Name {} -WorkDir {}\nTest-NeoNexusPort -Label {} -Port {}\nTest-NeoNexusPort -Label {} -Port {}\n",
            ps_literal(&format!("{} binary", node.name)),
            ps_literal(&node.binary_path),
            ps_literal(&format!("{} config", node.name)),
            ps_literal(&node.config_path),
            ps_literal(&format!("{} config", node.name)),
            ps_literal(&node.config_path),
            ps_literal(&node.config_sha256),
            ps_literal(&format!("{} workdir", node.name)),
            ps_literal(&node.working_dir),
            ps_literal(&node.name),
            ps_literal(&node.working_dir),
            ps_literal(&format!("{} RPC", node.name)),
            node.rpc_port,
            ps_literal(&format!("{} P2P", node.name)),
            node.p2p_port
        ));
        if let Some(ws_port) = node.ws_port {
            text.push_str(&format!(
                "Test-NeoNexusPort -Label {} -Port {}\n",
                ps_literal(&format!("{} WS", node.name)),
                ws_port
            ));
        }
        text.push('\n');
    }
    append_windows_signer_preflight(&mut text, manifest);
    text.push_str(
        "if ($Failures -ne 0) {\n    Write-Host 'Preflight failed'\n    exit 1\n}\n\nWrite-Host 'Preflight passed'\n",
    );
    text
}

fn append_windows_signer_preflight(text: &mut String, manifest: &DeploymentManifest) {
    if manifest.committee.signers.is_empty() {
        return;
    }
    text.push_str("# Committee signer references\n");
    for signer in &manifest.committee.signers {
        if let Some(plan) = &signer.signer_command_plan {
            text.push_str(&format!(
                "Test-NeoNexusSignerCommand -Label {} -Binary {}\n",
                ps_literal(&signer.label),
                ps_literal(&plan.binary)
            ));
        }
        if let Some(wallet_path) = &signer.wallet_path {
            if is_posix_absolute_path(wallet_path) {
                text.push_str(&format!(
                    "Warn-NeoNexusCheck {}\n",
                    ps_literal(&format!(
                        "{} wallet path is POSIX-style; skipping on Windows: {wallet_path}",
                        signer.label
                    ))
                ));
            } else {
                text.push_str(&format!(
                    "Test-NeoNexusFile -Label {} -Path {}\n",
                    ps_literal(&format!("{} wallet", signer.label)),
                    ps_literal(wallet_path)
                ));
            }
        }
        if let Some(endpoint) = &signer.signer_endpoint {
            if signer.signer_command_plan.is_some() {
                text.push_str(&format!(
                    "Warn-NeoNexusCheck {}\n",
                    ps_literal(&format!(
                        "{} endpoint will be checked after sidecar start: {endpoint}",
                        signer.label
                    ))
                ));
            } else {
                text.push_str(&format!(
                    "Test-NeoNexusSignerEndpoint -Label {} -Endpoint {}\n",
                    ps_literal(&signer.label),
                    ps_literal(endpoint)
                ));
            }
        }
    }
    text.push('\n');
}
