apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo-x.fullname" . }}
  labels:
    app: neo-x
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.node.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.node.wsPort }}
      targetPort: ws
      protocol: TCP
      name: ws
    - port: {{ .Values.node.p2pPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
  selector:
    app: neo-x
