//! Neo X configuration.
//!
//! Neo X is an EVM sidechain, so nothing the Neo N3 generators produce applies
//! here: no network magic, no `host:port` seed list, no standby committee, no
//! plugin sidecars. Its two clients do not even share a config schema —
//! Neo X Geth reads go-ethereum's `gethConfig` TOML, while neox-rs reads
//! Reth's, which holds no ports at all.

mod geth;
mod reth;

use anyhow::Result;

use crate::types::{NodeConfig, NodeType};

use super::super::format::RuntimeConfigProfile;
use super::ConfigGenerator;

impl ConfigGenerator {
    /// The config file for a Neo X node, in the schema its own client reads.
    pub fn neox_toml(node: &NodeConfig, profile: Option<&RuntimeConfigProfile>) -> Result<String> {
        match node.node_type {
            NodeType::NeoXGeth => geth::geth_toml(node, profile),
            NodeType::NeoXReth => reth::reth_toml(node, profile),
            other => anyhow::bail!("{other} is not a Neo X client"),
        }
    }
}

/// A comment block above the rendered TOML.
///
/// Both clients keep operator-critical settings outside the config file, and a
/// file that silently omits them reads as if they were defaults. The header is
/// where that is said.
fn header(preamble: &str) -> String {
    let body: String = preamble
        .lines()
        .map(|line| {
            if line.starts_with('#') {
                format!("{line}\n")
            } else {
                format!("# {line}\n")
            }
        })
        .collect();
    format!("# Generated by NeoNexus.\n{body}\n")
}
