version: '3.8'

services:
  # Neo N3 Go Client (neo-go)
  neo-go:
    image: nspccdev/neo-go:0.106.0
    container_name: neo-go-node
    command: node --config-path /config --relative-path
    volumes:
      - neo-data:/data
      - ../helm/neo-go/templates/configmap.yaml:/config/protocol.mainnet.yml
    ports:
      - "10332:10332" # RPC
      - "10333:10333" # P2P
      - "2112:2112"   # Prometheus Metrics
    restart: unless-stopped
    networks:
      - neo-net

  # Prometheus for scraping neo-go metrics
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - neo-net

  # Grafana for visualizing the node metrics
  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=neonexus
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - neo-net

networks:
  neo-net:
    driver: bridge

volumes:
  neo-data:
  prom-data:
  grafana-data:
