use super::RequiredTable;

pub(super) const RUNTIME_ASSET_TABLES: &[RequiredTable] = &[
    RequiredTable {
        name: "fast_sync_snapshots",
        columns: &[
            "id",
            "label",
            "network",
            "node_type",
            "source_path",
            "source_url",
            "download_file_name",
            "download_max_bytes",
            "expected_sha256",
            "cached_path",
            "verified_sha256",
            "verified_at_unix",
            "bytes",
        ],
    },
    RequiredTable {
        name: "runtime_installations",
        columns: &[
            "package_id",
            "label",
            "node_type",
            "version",
            "os",
            "arch",
            "binary_path",
            "sha256",
            "signature_verified",
            "signer_public_key",
            "bytes",
            "installed_at_unix",
        ],
    },
    RequiredTable {
        name: "runtime_catalog_profiles",
        columns: &[
            "id",
            "label",
            "source",
            "signature_source",
            "ed25519_public_key",
            "max_bytes",
            "enabled",
            "last_loaded_at_unix",
            "last_signature_verified",
            "last_bytes",
        ],
    },
    RequiredTable {
        name: "runtime_signer_profiles",
        columns: &[
            "id",
            "label",
            "ed25519_public_key",
            "enabled",
            "created_at_unix",
            "last_used_at_unix",
        ],
    },
    RequiredTable {
        name: "neo_wallet_profiles",
        columns: &[
            "id",
            "label",
            "source_path",
            "wallet_version",
            "primary_address",
            "contract_public_keys",
            "wallet_sha256",
            "account_count",
            "encrypted_account_count",
            "default_account_count",
            "watch_only_account_count",
            "validated_at_unix",
            "last_used_at_unix",
        ],
    },
];
