use super::version_text;

pub(in crate::cli) fn help_text() -> String {
    [
        version_text(),
        help_section(USAGE_LINES),
        help_section(APPLICATION_MODE_LINES),
        help_section(OPTION_LINES),
        help_section(CONFIG_GENERATION_LINES),
        help_section(WALLET_PROFILE_LINES),
        help_section(ALERT_ROUTING_LINES),
        help_section(NATIVE_BOUNDARY_LINES),
        help_section(SOURCE_QUALITY_LINES),
        help_section(NODE_CONTROL_LINES),
    ]
    .join("\n\n")
}

fn help_section(lines: &[&str]) -> String {
    lines.join("\n")
}

const USAGE_LINES: &[&str] = &[
    "USAGE:",
    "  neo-nexus [--web|--version|--self-check|--help]",
    "  neo-nexus --completions <bash|zsh|fish>",
    "  neo-nexus --runtime-smoke <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <binary> [runtime-args...]",
    "  neo-nexus --runtime-smoke-json <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <binary> [runtime-args...]",
    "  neo-nexus --designation <rpc-endpoint> <role> [public-key]",
    "  neo-nexus --designation-json <rpc-endpoint> <role> [public-key]",
    "  neo-nexus --governance <rpc-endpoint>",
    "  neo-nexus --governance-json <rpc-endpoint>",
    "  neo-nexus --rpc-health <port|url>",
    "  neo-nexus --rpc-health-json <port|url>",
    "  neo-nexus --workspace-readiness <neonexus.db>",
    "  neo-nexus --workspace-readiness-json <neonexus.db>",
    "  neo-nexus --workspace-metrics <neonexus.db>",
    "  neo-nexus --workspace-metrics-json <neonexus.db>",
    "  neo-nexus --workspace-metrics-prometheus <neonexus.db>",
    "  neo-nexus --workspace-integrity <neonexus.db>",
    "  neo-nexus --workspace-integrity-json <neonexus.db>",
    "  neo-nexus --source-purity <repo-dir>",
    "  neo-nexus --source-purity-json <repo-dir>",
    "  neo-nexus --source-quality <source-dir>",
    "  neo-nexus --source-quality-json <source-dir>",
    "  neo-nexus --ci-policy <workflow.yml>",
    "  neo-nexus --ci-policy-json <workflow.yml>",
    "  neo-nexus --export-readiness-report <neonexus.db> <output-dir>",
    "  neo-nexus --export-support-bundle <neonexus.db> <output-dir>",
    "  neo-nexus --export-support-bundle-json <neonexus.db> <output-dir>",
    "  neo-nexus --export-event-journal <neonexus.db> <output-dir> [limit] [info|warning|critical|all] [query...]",
    "  neo-nexus --export-node-configs <neonexus.db> <output-dir>",
    "  neo-nexus --export-node-configs-json <neonexus.db> <output-dir>",
    "  neo-nexus --validate-node-config <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <mainnet|testnet|private> <leveldb|rocksdb> <rpc-port> <p2p-port> <config-path>",
    "  neo-nexus --validate-node-config-json <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <mainnet|testnet|private> <leveldb|rocksdb> <rpc-port> <p2p-port> <config-path>",
    "  neo-nexus --export-backup <neonexus.db> <output-dir>",
    "  neo-nexus --export-backup-json <neonexus.db> <output-dir>",
    "  neo-nexus --import-backup <neonexus.db> <backup.json>",
    "  neo-nexus --import-backup-json <neonexus.db> <backup.json>",
    "  neo-nexus --validate-backup <backup.json>",
    "  neo-nexus --validate-backup-json <backup.json>",
    "  neo-nexus --validate-wallet <wallet.json>",
    "  neo-nexus --validate-wallet-json <wallet.json>",
    "  neo-nexus --validate-launch-pack <manifest.json|launch-pack-dir>",
    "  neo-nexus --launch-pack-sidecars <manifest.json|launch-pack-dir>",
    "  neo-nexus --launch-pack-sidecars-json <manifest.json|launch-pack-dir>",
    "  neo-nexus --package-release <output-dir>",
    "  neo-nexus --verify-release-package <dist-dir|manifest.json|archive.zip> <trusted-ed25519-public-key-base64> <manifest.sig>",
    "  neo-nexus --verify-release-package-json <dist-dir|manifest.json|archive.zip> <trusted-ed25519-public-key-base64> <manifest.sig>",
    "  neo-nexus --verify-release-package-integrity <dist-dir|manifest.json|archive.zip>",
    "  neo-nexus --verify-release-package-integrity-json <dist-dir|manifest.json|archive.zip>",
    "  neo-nexus --node-start <neonexus.db> <node-name>",
    "  neo-nexus --node-stop <neonexus.db> <node-name>",
    "  neo-nexus --node-restart <neonexus.db> <node-name>",
    "  neo-nexus --node-rebind-runtime <neonexus.db> <node-name> <binary> [runtime-args...]",
    "  neo-nexus --node-status <neonexus.db> <node-name>",
    "  neo-nexus --node-status-json <neonexus.db> <node-name>",
    "  neo-nexus --fleet-health <neonexus.db>",
    "  neo-nexus --fleet-health-json <neonexus.db>",
    "  neo-nexus --node-health <neonexus.db> <node-name>",
    "  neo-nexus --node-health-json <neonexus.db> <node-name>",
    "  neo-nexus --node-list <neonexus.db>",
    "  neo-nexus --node-list-json <neonexus.db>",
    "  neo-nexus --list-api-tokens <neonexus.db>",
    "  neo-nexus --list-api-tokens-json <neonexus.db>",
    "  neo-nexus --create-api-token <neonexus.db> <name> [permission]",
    "  neo-nexus --revoke-api-token <neonexus.db> <token-id>",
];

const APPLICATION_MODE_LINES: &[&str] = &[
    "APPLICATION MODE:",
    "  neo-nexus           Start the web workbench and open it from a browser",
    "  --web               Start the web workbench explicitly",
    "  --bind / --port     Web workbench bind address (default 127.0.0.1) and port (default 8080)",
    "  --web-token-file    Read the operator sign-in token from a protected file",
    "  --web-public-origin Browser-facing HTTPS origin (required for non-loopback bind)",
    "  all other options   Run a headless manager command and exit",
    "Without an option, NeoNexus starts the web workbench server.",
];

const OPTION_LINES: &[&str] = &[
    "OPTIONS:",
    "  --web                        Start the web workbench server (the default with no options)",
    "  --bind / --port              Web workbench bind address and port",
    "  --web-token-file             Protected operator-token file for the web workbench",
    "  --web-public-origin          Browser-facing HTTPS origin for cookie and request security",
    "  --version                    Print version and exit",
    "  --self-check                 Verify native runtime prerequisites and exit",
    "  --completions                Print a shell completion script (bash, zsh, or fish)",
    "  --runtime-smoke              Run a bounded runtime binary probe headlessly",
    "  --runtime-smoke-json         Print runtime smoke probe results as JSON",
    "  --designation                Audit committee role designation headlessly",
    "  --designation-json           Print designation audit as JSON",
    "  --governance                 Inspect governance committee state headlessly",
    "  --governance-json            Print governance inspection as JSON",
    "  --rpc-health                 Probe a node's RPC health headlessly",
    "  --rpc-health-json            Print RPC health probe results as JSON",
    "  --workspace-readiness        Audit workspace health blockers headlessly",
    "  --workspace-readiness-json   Print workspace readiness audit as JSON",
    "  --workspace-metrics          Print a point-in-time workspace metrics snapshot",
    "  --workspace-metrics-json     Print workspace metrics as JSON",
    "  --workspace-metrics-prometheus Print workspace metrics in Prometheus text format",
    "  --workspace-integrity        Check SQLite database and workspace directory integrity",
    "  --workspace-integrity-json   Print workspace integrity check results as JSON",
    "  --source-purity              Verify pure-Rust source tree (no web/tauri artifacts)",
    "  --source-purity-json         Print source tree purity check results as JSON",
    "  --source-quality             Scan repository source files against quality rules",
    "  --source-quality-json        Print source quality scan results as JSON",
    "  --ci-policy                  Validate CI workflow file against repository policy",
    "  --ci-policy-json             Print CI policy validation results as JSON",
    "  --alert-preview              Preview an alert payload formatted for a given provider",
    "  --alert-preview-json         Print previewed alert payload as JSON",
    "  --export-readiness-report    Export a detailed readiness report (readiness.txt + readiness.json)",
    "  --export-support-bundle      Export an operator support bundle with configs, logs, and diagnostics",
    "  --export-support-bundle-json Export support bundle and print manifest as JSON",
    "  --export-event-journal       Export runtime event journal entries to a file",
    "  --export-node-configs        Export generated node configuration files to a directory",
    "  --export-node-configs-json   Export node configs and print manifest as JSON",
    "  --generate-node-config       Generate a primary node configuration file headlessly",
    "  --generate-node-config-json  Generate a node configuration file and print result as JSON",
    "  --validate-node-config       Validate a node configuration file headlessly",
    "  --validate-node-config-json  Validate a node configuration file and print result as JSON",
    "  --export-backup              Write a 0600 plaintext JSON workspace export, NOT encrypted",
    "  --export-backup-json         Export backup and print manifest as JSON",
    "  --import-backup              Import a previously exported workspace backup file",
    "  --import-backup-json         Import backup and print result as JSON",
    "  --validate-backup            Inspect and validate a backup file without importing",
    "  --validate-backup-json       Validate backup file and print result as JSON",
    "  --validate-wallet            Validate an encrypted NEP-6 Neo wallet file",
    "  --validate-wallet-json       Print encrypted NEP-6 wallet validation as JSON",
    "  --validate-launch-pack       Validate a private-network launch pack headlessly",
    "  --launch-pack-sidecars       Print supervisor-ready signer sidecar specs from a launch pack",
    "  --launch-pack-sidecars-json  Print launch pack signer sidecar specs as JSON",
    "  --package-release            Package the current native executable with integrity metadata",
    "  --verify-release-package     Authenticate a canonical manifest with an explicit Ed25519 trust anchor, then verify integrity",
    "  --verify-release-package-json Print authenticated release verification as JSON",
    "  --verify-release-package-integrity Verify ZIP structure, manifests, limits, checksums, and hashes without claiming publisher authenticity",
    "  --verify-release-package-integrity-json Print explicitly integrity-only verification as JSON",
    "  --node-start                 Start a node headlessly via the shared core pipeline",
    "  --node-stop                  Stop a node headlessly via the shared supervisor",
    "  --node-restart               Restart a node headlessly via the shared core path",
    "  --node-rebind-runtime        Trust a local binary/argv for an imported node and clear quarantine",
    "  --node-status                Print a detailed single-node report (status, ports, RPC health)",
    "  --node-status-json           Print a detailed single-node report as JSON",
    "  --fleet-health               Report every node's chain health, worst first; exits 1 if any needs attention",
    "  --fleet-health-json          Print fleet chain health as JSON; exits 1 if any node needs attention",
    "  --node-health                Report one node's verdict, readings and state history",
    "  --node-health-json           Print one node's chain health as JSON",
    "  --node-list                  List all nodes in a workspace as a compact table",
    "  --node-list-json             List all nodes in a workspace as JSON",
    "  --list-api-tokens            List all API authentication tokens in a workspace",
    "  --list-api-tokens-json       List all API authentication tokens as JSON",
    "  --create-api-token           Create and store a new API authentication token",
    "  --revoke-api-token           Revoke an existing API authentication token by ID",
    "  --help                       Print this help and exit",
];

const CONFIG_GENERATION_LINES: &[&str] = &[
    "CONFIG GENERATION:",
    "  neo-nexus --generate-node-config <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <mainnet|testnet|private> <leveldb|rocksdb> <rpc-port> <p2p-port> <output-path>",
    "  neo-nexus --generate-node-config-json <neo-cli|neo-go|neo-rs|neox-geth|neox-rs> <mainnet|testnet|private> <leveldb|rocksdb> <rpc-port> <p2p-port> <output-path>",
];

const WALLET_PROFILE_LINES: &[&str] = &[
    "WALLET PROFILES:",
    "  neo-nexus --import-wallet-profile <neonexus.db> <wallet.json> <profile-id> <label>",
];

const ALERT_ROUTING_LINES: &[&str] = &[
    "ALERT ROUTING:",
    "  neo-nexus --alert-preview <generic|slack|discord|telegram|pagerduty|opsgenie|datadog> <target-url> <info|warning|critical> <message...>",
    "  neo-nexus --alert-preview-json <generic|slack|discord|telegram|pagerduty|opsgenie|datadog> <target-url> <info|warning|critical> <message...>",
];

const NATIVE_BOUNDARY_LINES: &[&str] = &[
    "NATIVE BOUNDARY:",
    "  --source-purity also rejects WebView/Tauri Cargo dependencies, lockfile packages, and project files.",
];

const SOURCE_QUALITY_LINES: &[&str] = &[
    "SOURCE QUALITY:",
    "  --source-quality checks production markers, hardcoded platform shortcut labels, and repository maintenance file budgets.",
];

const NODE_CONTROL_LINES: &[&str] = &[
    "NODE CONTROL:",
    "  Start, stop, restart, or list nodes headlessly. These run the SAME core launch pipeline as",
    "  the web workbench (readiness -> managed config -> supervise -> persist status), so a scripted node and",
    "  an operator's node behave identically.",
    "  Imported backup commands stay quarantined until --node-rebind-runtime (or a local editor save) supplies a trusted binary and arguments.",
    "  --node-start / --node-stop / --node-restart / --node-status take the database and node name.",
    "  --node-list takes just the workspace database path.",
];
