use super::super::super::*;
use super::{channels::StartupChannels, policies::StartupPolicies};

pub(super) fn build_initial_app(
    repository: Repository,
    policies: StartupPolicies,
    channels: StartupChannels,
) -> NeoNexusApp {
    NeoNexusApp {
        repository,
        supervisor: ProcessSupervisor::default(),
        watchdog: Watchdog::new(policies.watchdog),
        watchdog_policy_draft: WatchdogPolicyDraft::from_policy(policies.watchdog),
        runtime_upgrade_policy_draft: RuntimeUpgradePolicyDraft::from_policy(
            &policies.runtime_upgrade,
        ),
        runtime_upgrade_policy: policies.runtime_upgrade,
        metrics: MetricsCollector::new(METRICS_REFRESH_INTERVAL),
        metrics_snapshot: MetricsSnapshot::empty(),
        nodes: Vec::new(),
        draft: NodeDraft::default(),
        snapshot_draft: SnapshotDraft::default(),
        snapshot_catalog_source: String::new(),
        snapshot_catalog_signature_source: String::new(),
        snapshot_catalog_public_key: String::new(),
        snapshot_catalog: None,
        snapshot_catalog_signature_verified: None,
        snapshot_catalog_bytes: 0,
        runtime_package_draft: RuntimePackageDraft::default(),
        runtime_catalog_profile_label: "Default runtime catalog".to_string(),
        runtime_catalog_source: String::new(),
        runtime_catalog_signature_source: String::new(),
        runtime_catalog_public_key: String::new(),
        runtime_catalog_profiles: Vec::new(),
        runtime_signer_profile_label: "Trusted runtime signer".to_string(),
        runtime_signer_public_key: String::new(),
        runtime_signer_profiles: Vec::new(),
        neo_wallet_profiles: Vec::new(),
        wallet_profile_source: String::new(),
        wallet_profile_id: "validator-wallet".to_string(),
        wallet_profile_label: "Validator wallet".to_string(),
        runtime_catalog: None,
        runtime_catalog_signature_verified: None,
        runtime_catalog_bytes: 0,
        remote_servers: Vec::new(),
        remote_server_name: "Remote NeoNexus".to_string(),
        remote_server_base_url: "https://".to_string(),
        remote_server_description: String::new(),
        remote_server_enabled: true,
        last_remote_server_probe: None,
        selected_view: View::Summary,
        selected_node: None,
        selected_plugin: None,
        plugin_package_source: String::new(),
        plugin_package_expected_sha256: String::new(),
        selected_snapshot: None,
        selected_snapshot_catalog_entry: None,
        selected_runtime_catalog_profile: None,
        selected_runtime_signer_profile: None,
        selected_neo_wallet_profile: None,
        selected_runtime_installation: None,
        selected_runtime_release: None,
        selected_remote_server: None,
        selected_role: NodeRole::RpcApi,
        private_network_template: PrivateNetworkTemplate::SevenNodeLab,
        private_network_runtime: NodeType::NeoRs,
        private_network_committee_keys: String::new(),
        private_network_signer_refs: String::new(),
        private_network_last_export_root: None,
        private_network_last_validation: None,
        private_network_sidecar_report: None,
        private_network_sidecar_health_report: None,
        private_network_sidecar_pids: BTreeMap::new(),
        private_network_allow_external_sidecars: policies.allow_external_sidecars,
        plugin_catalog: PluginCatalog,
        workspace_integrity_report: None,
        last_backup_validation: None,
        last_release_package: None,
        last_release_verification: None,
        notice: policies.notice,
        pending_delete_node: None,
        overview_fleet_page: 0,
        node_page: 0,
        node_query: String::new(),
        node_status_filter: None,
        plugin_page: 0,
        plugin_query: String::new(),
        plugin_enabled_filter: None,
        plugin_category_filter: None,
        config_page: 0,
        log_page: 0,
        log_query: String::new(),
        log_follow_tail: false,
        event_page: 0,
        selected_event: None,
        action_queue_page: 0,
        action_queue_query: String::new(),
        action_queue_severity_filter: None,
        action_queue_resolution_filter: None,
        selected_readiness_action: None,
        port_matrix_page: 0,
        port_matrix_query: String::new(),
        port_matrix_status_filter: None,
        port_matrix_network_filter: None,
        port_matrix_health_filter: None,
        readiness_check_page: 0,
        readiness_check_query: String::new(),
        readiness_check_severity_filter: None,
        readiness_check_resolution_filter: None,
        selected_readiness_check: None,
        snapshot_page: 0,
        snapshot_query: String::new(),
        snapshot_network_filter: None,
        snapshot_type_filter: None,
        snapshot_verified_filter: None,
        snapshot_cached_filter: None,
        snapshot_catalog_page: 0,
        snapshot_catalog_query: String::new(),
        snapshot_catalog_network_filter: None,
        snapshot_catalog_type_filter: None,
        runtime_page: 0,
        runtime_inventory_query: String::new(),
        runtime_inventory_type_filter: None,
        runtime_inventory_signed_filter: None,
        runtime_inventory_platform_filter: None,
        runtime_catalog_page: 0,
        runtime_catalog_query: String::new(),
        runtime_catalog_type_filter: None,
        runtime_catalog_platform_filter: None,
        monitor_process_page: 0,
        monitor_process_query: String::new(),
        monitor_process_state_filter: None,
        monitor_process_high_cpu_filter: false,
        monitor_process_high_memory_filter: false,
        selected_monitor_process: None,
        wallet_profile_page: 0,
        wallet_profile_query: String::new(),
        wallet_profile_used_filter: None,
        remote_server_page: 0,
        remote_server_query: String::new(),
        remote_server_enabled_filter: None,
        remote_probe_history_page: 0,
        remote_probe_history_query: String::new(),
        remote_probe_history_status_filter: None,
        alert_delivery_page: 0,
        alert_delivery_status_filter: None,
        alert_delivery_query: String::new(),
        alert_routing_policy: policies.alert_routing.clone(),
        alert_routing_policy_draft: AlertRoutingPolicyDraft::from_policy(&policies.alert_routing),
        last_alert_preview: None,
        last_alert_preview_policy: None,
        alert_delivery_pending: 0,
        alert_delivery_results: channels.alert_delivery_results,
        alert_delivery_sender: channels.alert_delivery_sender,
        event_query: String::new(),
        event_severity_filter: None,
        rpc_health_monitor_policy: policies.rpc_health_monitor,
        rpc_health_monitor_policy_draft: RpcHealthMonitorPolicyDraft::from_policy(
            policies.rpc_health_monitor,
        ),
        rpc_health_last_started: BTreeMap::new(),
        rpc_health_pending: BTreeSet::new(),
        rpc_health_results: channels.rpc_health_results,
        rpc_health_sender: channels.rpc_health_sender,
        remote_federation_monitor_policy: policies.remote_federation_monitor,
        remote_federation_monitor_policy_draft: RemoteFederationMonitorPolicyDraft::from_policy(
            policies.remote_federation_monitor,
        ),
        remote_federation_last_started: BTreeMap::new(),
        remote_federation_pending: BTreeSet::new(),
        remote_federation_results: channels.remote_federation_results,
        remote_federation_sender: channels.remote_federation_sender,
    }
}
